import aiohttp.web as web
import asyncio
import os
from datetime import datetime, timezone
import mimetypes
from aiofiles import open as aioopen
import logging
import sys
import hashlib
from pathlib import Path
import re
from supabase import create_client, Client
import base64
import uuid
import PyPDF2
from io import BytesIO
from dotenv import load_dotenv
from groq import Groq
import psycopg2


load_dotenv()   # 👈 THIS loads .env

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

groq_client = Groq(api_key=GROQ_API_KEY)

# ────────────────────────────────────────────────
# CONFIGURATION
# ────────────────────────────────────────────────
ADMIN_EMAIL = "zapierobroy77777559977@gmail.com"
SUPABASE_URL = "https://obnhesobzgppiidigdtu.supabase.co"
SUPABASE_KEY = "sb_publishable_-zpPTE45VhRROAZOV0xxFg_iTMVSYLA"
LOG_DIR = Path("logs")
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10 MB

# Native Postgres connection string — NOT the same as SUPABASE_KEY above.
# This is the one piece kept in .env instead of hardcoded here: it carries
# your DB password, and it's what lets the app create/verify its own
# tables on startup (see init_database() below) without you ever opening
# the Supabase SQL Editor.
# DATABASE_URL = os.getenv("DATABASE_URL")
# if not DATABASE_URL:
#     raise RuntimeError(
#         "DATABASE_URL is missing from .env. Get it from Supabase Dashboard "
#         "-> Project Settings -> Database -> Connection string -> URI, put "
#         "your DB password in it, and add it to .env as DATABASE_URL."
#     )

# Create directories
LOG_DIR.mkdir(exist_ok=True)

# Logging setup
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)-7s] %(name)-12s %(funcName)18s:%(lineno)4d → %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(LOG_DIR / "filemanager.log"),
        logging.FileHandler(LOG_DIR / "operations.log")
    ]
)
logger = logging.getLogger("filemanager")
operation_logger = logging.getLogger("operations")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# ────────────────────────────────────────────────
# AUTO DATABASE SETUP — this is the piece that replaces
# "go paste SQL into the Supabase SQL Editor". Every table/index
# below uses IF NOT EXISTS, so it's safe to run every single time
# the app starts — nothing gets dropped or duplicated.
# ────────────────────────────────────────────────
SCHEMA_SQL = """
create table if not exists public.users (
    id bigint generated by default as identity primary key,
    email varchar(180) not null unique,
    name varchar(120) not null,
    password_hash text not null,
    password_salt text not null,
    created_at timestamptz not null default now(),
    is_admin boolean not null default false
);

create table if not exists public.files (
    id bigint generated by default as identity primary key,
    filename varchar(255) not null,
    filetype varchar(50),
    size bigint not null default 0,
    uploaded_at timestamptz not null default now(),
    email varchar(180),
    md5_hash varchar(64),
    last_accessed timestamptz,
    status varchar(30) not null default 'active',
    download_count integer not null default 0,
    file_data text
);

create table if not exists public.urls (
    id bigint generated by default as identity primary key,
    url text not null,
    title text,
    short_code varchar(20) not null unique,
    email varchar(180),
    created_at timestamptz not null default now()
);

create table if not exists public.operations_log (
    id bigint generated by default as identity primary key,
    operation varchar(50) not null,
    file_id bigint,
    filename varchar(255),
    user_email varchar(180),
    operation_time timestamptz not null default now(),
    details text,
    success boolean not null default true,
    error_message text
);

create table if not exists public.chat_history (
    id bigint generated by default as identity primary key,
    session_id varchar(255) not null,
    user_email varchar(180),
    role varchar(30) not null,
    content text not null,
    file_name varchar(255),
    created_at timestamptz not null default now()
);

create index if not exists idx_users_email on public.users(email);
create index if not exists idx_files_filename on public.files(filename);
create index if not exists idx_files_email on public.files(email);
create index if not exists idx_files_status on public.files(status);
create index if not exists idx_files_uploaded_at on public.files(uploaded_at desc);
create index if not exists idx_urls_short_code on public.urls(short_code);
create index if not exists idx_urls_created_at on public.urls(created_at desc);
create index if not exists idx_operations_log_file_id on public.operations_log(file_id);
create index if not exists idx_operations_log_user_email on public.operations_log(user_email);
create index if not exists idx_operations_log_operation_time on public.operations_log(operation_time desc);
create index if not exists idx_chat_history_session_id on public.chat_history(session_id);
create index if not exists idx_chat_history_user_email on public.chat_history(user_email);
create index if not exists idx_chat_history_created_at on public.chat_history(created_at desc);
"""


def _create_tables_sync():
    """Runs the schema SQL over a real Postgres connection (psycopg2).
    This is the part the supabase-py REST client can't do."""
    conn = psycopg2.connect(DATABASE_URL)
    try:
        conn.autocommit = True
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)
        logger.info("✓ Schema verified/created: users, files, urls, operations_log, chat_history")
    finally:
        conn.close()


async def init_database():
    """Call once at startup. Safe to call every time the app boots."""
    logger.info("=" * 80)
    logger.info("CREATING / VERIFYING DATABASE TABLES")
    logger.info("=" * 80)
    loop = asyncio.get_event_loop()
    try:
        await loop.run_in_executor(None, _create_tables_sync)
    except Exception as e:
        logger.critical(f"Database setup failed: {e}", exc_info=True)
        raise RuntimeError(
            "Could not create/verify tables via DATABASE_URL. Check that the "
            "connection string (including password) is correct and that your "
            "network/firewall allows outbound connections to Supabase's DB port."
        ) from e
    logger.info("=" * 80)
    logger.info("DATABASE READY")
    logger.info("=" * 80)


# ────────────────────────────────────────────────
# HELPERS
# ────────────────────────────────────────────────
def safe_filename(original: str) -> str:
    """Sanitize filename - prevent path traversal & dangerous chars"""
    name = Path(original).name
    name = re.sub(r'[^a-zA-Z0-9._\-\u0600-\u06FF\s]', '_', name)
    if len(name) > 180:
        base, ext = os.path.splitext(name)
        name = base[:170] + ext
    return name

def calculate_file_hash(file_bytes: bytes, algorithm="md5") -> str | None:
    """Calculate hash from bytes"""
    try:
        hasher = hashlib.new(algorithm)
        hasher.update(file_bytes)
        return hasher.hexdigest()
    except Exception as e:
        logger.error(f"Hash calculation failed: {e}")
        return None

def log_operation(operation: str, file_id=None, filename=None, user_email=None,
                  success=True, details=None, error_message=None):
    try:
        data = {
            'operation': operation.upper(),
            'file_id': file_id,
            'filename': filename,
            'user_email': user_email,
            'operation_time': datetime.now(timezone.utc).isoformat(),
            'details': details,
            'success': success,
            'error_message': error_message
        }
        supabase.table('operations_log').insert(data).execute()
        msg = f"{operation:8} | {filename or '-':<35} | {user_email or '-':<28} | {'OK' if success else 'FAIL'}"
        if details: msg += f" | {details}"
        if error_message: msg += f" | {error_message}"
        if success:
            operation_logger.info(msg)
        else:
            operation_logger.error(msg)
    except Exception as e:
        logger.error(f"Operation logging failed: {e}")

# Wrapper to run Supabase sync calls in thread (non-blocking)
async def run_supabase_sync(func, *args, **kwargs):
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, lambda: func(*args, **kwargs))

# JSON Error Response Helper
def json_error(message, status=500):
    return web.json_response({"success": False, "message": message}, status=status)

# ────────────────────────────────────────────────
# MIDDLEWARE FOR JSON ERRORS
# ────────────────────────────────────────────────
async def json_error_middleware(app, handler):
    async def middleware_handler(request):
        try:
            response = await handler(request)
            return response
        except web.HTTPException as ex:
            return json_error(str(ex), ex.status)
        except Exception as ex:
            logger.error(f"Unhandled error: {ex}", exc_info=True)
            return json_error(f"Internal server error: {str(ex)}", 500)
    return middleware_handler

# ────────────────────────────────────────────────
# ROUTES - FILES STORED IN SUPABASE DB
# ────────────────────────────────────────────────
async def read_root(request):
    try:
        async with aioopen("index.html", "r", encoding="utf-8") as f:
            return web.Response(text=await f.read(), content_type='text/html')
    except FileNotFoundError:
        return web.Response(text="<h1>index.html not found</h1>", status=404)
    except Exception as e:
        logger.error(f"Root page error: {e}")
        raise web.HTTPInternalServerError()



async def last_read_root(request):
    try:
        async with aioopen("images.html", "r", encoding="utf-8") as f:
            return web.Response(text=await f.read(), content_type='text/html')
    except FileNotFoundError:
        return web.Response(text="<h1>images.html not found</h1>", status=404)
    except Exception as e:
        logger.error(f"Root page error: {e}")
        raise web.HTTPInternalServerError()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
WHITEBOARD_PATH = os.path.join(BASE_DIR, "whiteboard.html")

async def at_last_read_root(request):
    if not os.path.exists(WHITEBOARD_PATH):
        raise web.HTTPNotFound(text="whiteboard.html not found")
    return web.FileResponse(WHITEBOARD_PATH)


async def get_files(request):
    try:
        res = await run_supabase_sync(
            supabase.table('files')
            .select("id, filename, filetype, size, uploaded_at, email, download_count, last_accessed")
            .eq('status', 'active')
            .order('uploaded_at', desc=True)
            .execute
        )
        files = res.data or []
        total_size = sum(f['size'] for f in files)
        return web.json_response({
            "success": True,
            "files": files,
            "total_files": len(files),
            "total_size_bytes": total_size
        })
    except Exception as e:
        logger.error(f"get_files error: {e}", exc_info=True)
        raise

async def upload_file(request):
    original_name = None
    email = "anonymous@user.com"
    try:
        reader = await request.multipart()
        file_content = bytearray()
        while True:
            part = await reader.next()
            if part is None:
                break
            if part.name == "file":
                original_name = safe_filename(part.filename)
                async for chunk in part:
                    file_content.extend(chunk)
            elif part.name == "email":
                email = (await part.text()).strip()[:180]

        if not original_name or not file_content:
            log_operation("UPLOAD", user_email=email, success=False, error_message="Missing file")
            return json_error("File is required", 400)

        file_size = len(file_content)

        if file_size == 0:
            log_operation("UPLOAD", filename=original_name, user_email=email, success=False, error_message="Empty file")
            return json_error("Empty file not allowed. Please upload a file with content.", 400)

        if file_size > MAX_FILE_SIZE:
            log_operation("UPLOAD", filename=original_name, user_email=email, success=False, error_message="File too large")
            return json_error(f"File too large. Maximum size is {MAX_FILE_SIZE//1024//1024}MB", 413)

        # Check if file with same name already exists
        existing = await run_supabase_sync(
            supabase.table('files')
            .select("id")
            .eq('filename', original_name)
            .eq('status', 'active')
            .execute
        )

        if existing.data:
            log_operation("UPLOAD", filename=original_name, user_email=email, success=False, error_message="File already exists")
            return json_error(f"File '{original_name}' already exists. Please rename your file or delete the existing one first.", 409)

        # Calculate hash
        file_hash = calculate_file_hash(bytes(file_content))

        # Encode file content as base64 for storage in PostgreSQL
        file_b64 = base64.b64encode(bytes(file_content)).decode('utf-8')

        data = {
            "filename": original_name,
            "filetype": Path(original_name).suffix.lstrip('.').upper() or "FILE",
            "size": file_size,
            "uploaded_at": datetime.now(timezone.utc).isoformat(),
            "email": email,
            "md5_hash": file_hash,
            "last_accessed": datetime.now(timezone.utc).isoformat(),
            "status": "active",
            "download_count": 0,
            "file_data": file_b64  # Store base64 encoded file in DB
        }

        result = await run_supabase_sync(supabase.table('files').insert(data).execute)
        file_id = result.data[0]["id"]

        log_operation("UPLOAD", file_id, original_name, email, True,
                      f"Size: {file_size:,} Hash: {file_hash}")

        return web.json_response({
            "success": True,
            "message": f"File '{original_name}' uploaded successfully",
            "id": file_id,
            "filename": original_name,
            "size": file_size,
            "hash": file_hash
        })
    except web.HTTPException:
        raise
    except Exception as e:
        logger.error(f"Upload failed: {e}", exc_info=True)
        log_operation("UPLOAD", filename=original_name, user_email=email,
                      success=False, error_message=str(e))
        raise

async def download_file(request):
    try:
        file_id = int(request.match_info['file_id'])

        # Fetch file with data from DB
        res = await run_supabase_sync(
            supabase.table('files')
            .select("filename, size, md5_hash, download_count, file_data")
            .eq('id', file_id)
            .eq('status', 'active')
            .single()
            .execute
        )

        if not res.data:
            raise web.HTTPNotFound(text="File not found or deleted")

        file = res.data

        if not file.get('file_data'):
            log_operation("DOWNLOAD", file_id, file['filename'], None, False, error_message="File data missing")
            raise web.HTTPNotFound(text="File data not found in database")

        # Decode base64 file content
        try:
            file_bytes = base64.b64decode(file['file_data'])
        except Exception as e:
            logger.error(f"Failed to decode file data for ID {file_id}: {e}")
            raise web.HTTPInternalServerError(text="File data corrupted")

        mime, _ = mimetypes.guess_type(file['filename'])
        mime = mime or 'application/octet-stream'

        # Update download count
        current_count = file.get('download_count', 0)
        await run_supabase_sync(
            supabase.table('files')
            .update({"download_count": current_count + 1, "last_accessed": datetime.now(timezone.utc).isoformat()})
            .eq('id', file_id)
            .execute
        )

        log_operation("DOWNLOAD", file_id, file['filename'], success=True,
                      details=f"Size: {file['size']:,}")

        return web.Response(
            body=file_bytes,
            headers={
                "Content-Disposition": f'attachment; filename="{file["filename"]}"',
                "Content-Type": mime,
                "Content-Length": str(len(file_bytes)),
                "X-File-Hash": file["md5_hash"] or ""
            }
        )
    except web.HTTPException:
        raise
    except ValueError:
        raise web.HTTPBadRequest(text="Invalid file ID")
    except Exception as e:
        logger.error(f"Download error: {e}")
        raise


async def delete_file(request):
    try:
        file_id = int(request.match_info.get("file_id"))
    except (TypeError, ValueError):
        return json_error("Invalid file ID", 400)

    email = request.query.get("email", "").strip()

    if not email:
        try:
            data = await request.json()
            email = data.get("email", "").strip()
        except Exception:
            pass

    if not email:
        return json_error("Email is required", 400)

    logger.info(f"🗑️ HARD DELETE | file_id={file_id} | email={email}")

    if email != ADMIN_EMAIL:
        log_operation("DELETE", file_id, user_email=email,
                      success=False, error_message="Unauthorized")
        return json_error("Access denied (admin only)", 403)

    try:
        fetch_res = await run_supabase_sync(
            supabase.table("files")
            .select("id, filename, size")
            .eq("id", file_id)
            .single()
            .execute
        )

        if not fetch_res.data:
            return json_error("File not found", 404)

        file = fetch_res.data

        delete_res = await run_supabase_sync(
            supabase.table("files")
            .delete()
            .eq("id", file_id)
            .execute
        )

        verify_res = await run_supabase_sync(
            supabase.table("files")
            .select("id")
            .eq("id", file_id)
            .execute
        )

        if verify_res.data:
            return json_error("Delete failed: row still exists", 500)

        log_operation(
            "DELETE",
            file_id,
            file["filename"],
            email,
            True,
            f"Size: {file['size']:,}"
        )

        return web.json_response({
            "success": True,
            "message": f"File '{file['filename']}' permanently deleted"
        })

    except Exception as e:
        logger.error("🔥 Hard delete failed", exc_info=True)
        log_operation("DELETE", file_id, user_email=email,
                      success=False, error_message=str(e))
        return json_error("Internal server error", 500)

async def update_file(request):
    try:
        file_id = int(request.match_info.get("file_id"))
    except (TypeError, ValueError):
        return json_error("Invalid file ID", 400)

    try:
        reader = await request.multipart()
        new_content = bytearray()
        new_filename = None
        email = None

        while True:
            part = await reader.next()
            if part is None:
                break

            if part.name == "file":
                new_filename = safe_filename(part.filename)
                async for chunk in part:
                    new_content.extend(chunk)

            elif part.name == "email":
                email = (await part.text()).strip()

        if not email:
            return json_error("Email is required", 400)

        if email != ADMIN_EMAIL:
            log_operation("UPDATE", file_id, user_email=email,
                          success=False, error_message="Unauthorized")
            return json_error("Access denied (admin only)", 403)

        if not new_filename or not new_content:
            return json_error("File is required for update", 400)

        new_size = len(new_content)

        if new_size > MAX_FILE_SIZE:
            return json_error(
                f"File too large. Max {MAX_FILE_SIZE // 1024 // 1024}MB",
                413
            )

        old_res = await run_supabase_sync(
            supabase.table("files")
            .select("id, filename")
            .eq("id", file_id)
            .single()
            .execute
        )

        if not old_res.data:
            return json_error("File not found", 404)

        new_hash = calculate_file_hash(bytes(new_content))
        file_b64 = base64.b64encode(bytes(new_content)).decode("utf-8")

        update_payload = {
            "filename": new_filename,
            "filetype": Path(new_filename).suffix.lstrip(".").upper() or "FILE",
            "size": new_size,
            "md5_hash": new_hash,
            "last_accessed": datetime.now(timezone.utc).isoformat(),
            "file_data": file_b64
        }

        await run_supabase_sync(
            supabase.table("files")
            .update(update_payload)
            .eq("id", file_id)
            .execute
        )

        verify_res = await run_supabase_sync(
            supabase.table("files")
            .select("filename, size, md5_hash")
            .eq("id", file_id)
            .single()
            .execute
        )

        if not verify_res.data:
            return json_error(
                "Update failed: row not found after update",
                500
            )

        if verify_res.data["md5_hash"] != new_hash:
            return json_error(
                "Update blocked by database policy (RLS)",
                403
            )

        log_operation(
            "UPDATE",
            file_id,
            new_filename,
            email,
            True,
            f"Size: {new_size:,} Hash: {new_hash}"
        )

        return web.json_response({
            "success": True,
            "message": f"File '{new_filename}' updated successfully",
            "filename": new_filename,
            "size": new_size,
            "hash": new_hash
        })

    except web.HTTPException:
        raise

    except Exception as e:
        logger.error("🔥 Update failed", exc_info=True)
        log_operation(
            "UPDATE",
            file_id,
            success=False,
            error_message=str(e)
        )
        return json_error("Internal server error", 500)


async def save_url(request):
    try:
        reader = await request.multipart()
        url = None
        title = None
        email = "anonymous@user.com"
        while True:
            part = await reader.next()
            if part is None:
                break
            if part.name == "url":
                url = (await part.text()).strip()
            elif part.name == "title":
                title = (await part.text()).strip()
            elif part.name == "email":
                email = (await part.text()).strip()[:180] or email

        if not url:
            raise web.HTTPBadRequest(text="url is required")

        if not title:
            title = url

        import random
        import string
        max_attempts = 10
        short_code = None

        for attempt in range(max_attempts):
            timestamp = str(int(datetime.now(timezone.utc).timestamp() * 1000))
            random_part = ''.join(random.choices(string.ascii_letters + string.digits, k=3))
            short_code = hashlib.md5(f"{timestamp}{random_part}".encode()).hexdigest()[:5]

            existing = await run_supabase_sync(
                supabase.table('urls')
                .select("id")
                .eq('short_code', short_code)
                .execute
            )

            if not existing.data:
                break
            short_code = None

        if not short_code:
            raise RuntimeError("Could not generate unique short code after multiple attempts")

        result = await run_supabase_sync(
            supabase.table('urls')
            .insert({
                "url": url,
                "title": title,
                "short_code": short_code,
                "email": email,
                "created_at": datetime.now(timezone.utc).isoformat()
            })
            .execute
        )

        return web.json_response({
            "success": True,
            "id": result.data[0]["id"],
            "short_code": short_code,
            "message": "URL saved"
        })
    except Exception as e:
        logger.error(f"Save URL error: {e}")
        raise

async def get_urls(request):
    try:
        res = await run_supabase_sync(
            supabase.table('urls')
            .select("id, url, title, short_code, email, created_at")
            .order('created_at', desc=True)
            .execute
        )
        return web.json_response({
            "success": True,
            "urls": res.data or [],
            "total": len(res.data or [])
        })
    except Exception as e:
        logger.error(f"Get URLs error: {e}")
        raise

async def url_redirect(request):
    try:
        url_id = int(request.match_info['url_id'])
    except (ValueError, KeyError):
        return web.Response(text="Invalid URL ID", status=400)

    try:
        res = await run_supabase_sync(
            supabase.table('urls')
            .select("url")
            .eq('id', url_id)
            .single()
            .execute
        )

        if not res.data or not res.data.get('url'):
            return web.Response(text="URL not found", status=404)

        target_url = res.data["url"]

        if not target_url.startswith(('http://', 'https://')):
            target_url = 'https://' + target_url

        logger.info(f"Redirecting URL ID {url_id} to {target_url}")

        return web.Response(
            status=302,
            headers={'Location': target_url}
        )

    except Exception as e:
        logger.error(f"URL redirect error: {e}", exc_info=True)
        return web.Response(text=f"Redirect failed: {str(e)}", status=500)

async def delete_url(request):
    try:
        url_id = int(request.match_info['url_id'])
    except (ValueError, KeyError):
        return json_error("Invalid URL ID", 400)

    email = request.query.get('email', '').strip()

    if not email:
        try:
            data = await request.json()
            email = data.get('email', '').strip()
        except Exception:
            pass

    if not email:
        try:
            post_data = await request.post()
            email = post_data.get('email', '').strip()
        except Exception:
            pass

    logger.info(f"Delete URL request for ID {url_id} with email: {email}")

    if not email:
        return json_error("Email is required for deletion", 400)

    if email != ADMIN_EMAIL:
        logger.warning(f"Unauthorized URL delete attempt by {email} for URL ID {url_id}")
        return json_error(f"Access denied. Only admin ({ADMIN_EMAIL}) can delete URLs.", 403)

    try:
        res = await run_supabase_sync(
            supabase.table('urls')
            .select("id, url, title")
            .eq('id', url_id)
            .single()
            .execute
        )

        if not res.data:
            return json_error("URL not found", 404)

        url_data = res.data

        await run_supabase_sync(
            supabase.table('urls')
            .delete()
            .eq('id', url_id)
            .execute
        )

        logger.info(f"URL deleted: ID={url_id}, Title='{url_data['title']}', By={email}")

        return web.json_response({
            "success": True,
            "message": f"URL '{url_data['title']}' deleted successfully"
        })

    except web.HTTPException:
        raise
    except Exception as e:
        logger.error(f"Delete URL failed: {e}", exc_info=True)
        return json_error(f"Failed to delete URL: {str(e)}", 500)


# ────────────────────────────────────────────────
# AUTH (email + password, Supabase-backed)
# ────────────────────────────────────────────────
def hash_password(password: str, salt: str = None) -> tuple[str, str]:
    """PBKDF2-SHA256 password hash. Returns (hash_hex, salt_hex)."""
    if salt is None:
        salt = uuid.uuid4().hex
    dk = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt.encode('utf-8'), 120_000)
    return dk.hex(), salt

def verify_password(password: str, stored_hash: str, salt: str) -> bool:
    check, _ = hash_password(password, salt)
    return check == stored_hash

async def auth_signup(request):
    try:
        data = await request.json()
        email = (data.get('email') or '').strip().lower()[:180]
        password = data.get('password') or ''
        name = (data.get('name') or email.split('@')[0]).strip()[:120]

        if not email or '@' not in email:
            return json_error("Valid email is required", 400)
        if len(password) < 6:
            return json_error("Password must be at least 6 characters", 400)

        existing = await run_supabase_sync(
            supabase.table('users').select("id").eq('email', email).execute
        )
        if existing.data:
            return json_error("An account with this email already exists", 409)

        pw_hash, salt = hash_password(password)
        result = await run_supabase_sync(
            supabase.table('users').insert({
                "email": email,
                "name": name,
                "password_hash": pw_hash,
                "password_salt": salt,
                "created_at": datetime.now(timezone.utc).isoformat(),
                "is_admin": email == ADMIN_EMAIL
            }).execute
        )
        log_operation("SIGNUP", user_email=email, success=True)
        return web.json_response({
            "success": True,
            "message": "Account created",
            "user": {"email": email, "name": name, "is_admin": email == ADMIN_EMAIL}
        })
    except web.HTTPException:
        raise
    except Exception as e:
        logger.error(f"Signup failed: {e}", exc_info=True)
        return json_error("Signup failed", 500)

async def auth_login(request):
    try:
        data = await request.json()
        email = (data.get('email') or '').strip().lower()[:180]
        password = data.get('password') or ''

        if not email or not password:
            return json_error("Email and password are required", 400)

        res = await run_supabase_sync(
            supabase.table('users').select("*").eq('email', email).single().execute
        )
        if not res.data:
            log_operation("LOGIN", user_email=email, success=False, error_message="No such user")
            return json_error("Invalid email or password", 401)

        user = res.data
        if not verify_password(password, user['password_hash'], user['password_salt']):
            log_operation("LOGIN", user_email=email, success=False, error_message="Bad password")
            return json_error("Invalid email or password", 401)

        token = uuid.uuid4().hex
        AUTH_TOKENS[token] = email
        log_operation("LOGIN", user_email=email, success=True)
        return web.json_response({
            "success": True,
            "token": token,
            "user": {"email": email, "name": user.get('name'), "is_admin": email == ADMIN_EMAIL}
        })
    except web.HTTPException:
        raise
    except Exception as e:
        logger.error(f"Login failed: {e}", exc_info=True)
        return json_error("Invalid email or password", 401)

# in-memory token store (simple session; swap for JWT/redis in production)
AUTH_TOKENS = {}

async def auth_me(request):
    token = request.headers.get('X-Auth-Token') or request.query.get('token')
    email = AUTH_TOKENS.get(token)
    if not email:
        return json_error("Not authenticated", 401)
    return web.json_response({"success": True, "email": email, "is_admin": email == ADMIN_EMAIL})


class SessionManager:
    def __init__(self):
        self.sessions = {}

    def create_session(self, user_email=None):
        session_id = str(uuid.uuid4())
        self.sessions[session_id] = {
            'history': [],
            'pages': [],
            'current_page': 0,
            'file_data': None,
            'file_name': None,
            'file_type': None,
            'user_email': user_email or 'anonymous@user.com'
        }
        return session_id

    def get_session(self, session_id):
        return self.sessions.get(session_id)

    def add_to_history(self, session_id, role, content):
        if session_id in self.sessions:
            history = self.sessions[session_id]['history']
            history.append({
                'role': role,
                'content': content
            })

            if len(history) > 10:
                self.sessions[session_id]['history'] = history[-10:]

            try:
                text_content = content if isinstance(content, str) else str(content)
                supabase.table('chat_history').insert({
                    "session_id": session_id,
                    "user_email": self.sessions[session_id].get('user_email', 'anonymous@user.com'),
                    "role": role,
                    "content": text_content[:8000],
                    "file_name": self.sessions[session_id].get('file_name'),
                    "created_at": datetime.now(timezone.utc).isoformat()
                }).execute()
            except Exception as e:
                logger.error(f"chat_history persist failed: {e}")

    def set_file_data(self, session_id, file_data, filename, file_type):
        if session_id in self.sessions:
            self.sessions[session_id]['file_data'] = file_data
            self.sessions[session_id]['file_name'] = filename
            self.sessions[session_id]['file_type'] = file_type

    def add_page(self, session_id, file_data, filename, file_type):
        if session_id not in self.sessions:
            return None
        session = self.sessions[session_id]
        page = {'data': file_data, 'name': filename, 'type': file_type}
        session['pages'].append(page)
        self.set_file_data(session_id, file_data, filename, file_type)
        return len(session['pages']) - 1

    def set_current_page(self, session_id, index):
        if session_id not in self.sessions:
            return False
        session = self.sessions[session_id]
        if 0 <= index < len(session['pages']):
            session['current_page'] = index
            page = session['pages'][index]
            self.set_file_data(session_id, page['data'], page['name'], page['type'])
            return True
        return False

session_manager = SessionManager()

def get_mime_type(filename):
    ext = filename.lower().split('.')[-1]
    mime_types = {
        'pdf': 'application/pdf',
        'png': 'image/png',
        'jpg': 'image/jpeg',
        'jpeg': 'image/jpeg',
        'bmp': 'image/bmp',
        'tiff': 'image/tiff',
        'gif': 'image/gif',
        'webp': 'image/webp'
    }
    return mime_types.get(ext, 'application/octet-stream')

def check_pdf_pages(file_data):
    try:
        pdf_reader = PyPDF2.PdfReader(BytesIO(file_data))
        return len(pdf_reader.pages)
    except Exception:
        return 0


def create_system_prompt():
    return """You are a professional AI Knowledge Assistant, deployed as part of an enterprise document-intelligence platform. Respond the way a well-trained corporate support specialist would: courteous, precise, structured, and confident — never casual slang, never over-familiar.

CRITICAL RULES - FOLLOW EXACTLY:

1. ONLY use the provided uploaded document/image content.
   - DO NOT use external knowledge.
   - DO NOT guess.
   - DO NOT hallucinate.

2. NEVER generate:
   - Duplicate questions
   - Duplicate options
   - Incorrect question numbers
   - Mismatched options for a question
   - Repeated explanations

3. If generating multiple questions (e.g., "generate 20 questions"):
   - Number them sequentially (1, 2, 3 ... 20).
   - Ensure each question is UNIQUE.
   - Ensure each question is derived directly from the document.
   - Ensure options belong ONLY to that specific question.
   - Validate internally before responding that no question or option is repeated.

4. If asked about a specific question number (e.g., "question 5", "Q7"):
   - Locate EXACT matching question from the document.
   - Confirm the question text matches the document.
   - Identify correct option accurately.
   - Provide explanation in 3 levels:
        a) Beginner level (basic concept)
        b) Intermediate reasoning
        c) Advanced detailed explanation
   - Clearly state WHY the correct option is correct.
   - Clearly state WHY other options are incorrect (if applicable).

5. For questions NOT present in the document:
   - Respond EXACTLY:
     "I apologize, but I can only answer questions based on the uploaded document. The information about [topic] is not present in the provided content. Please ask questions related to the document."

6. For greetings (hi, hello, how are you):
   - Respond briefly, warmly, and professionally, the way a corporate helpdesk agent would greet a client.
   - Remind the user you only answer based on the uploaded document.

7. Tone and formatting standards (MNC helpdesk style):
   - Open with a brief acknowledgement when helpful (e.g., "Certainly," "Understood,").
   - Use clear headings/bullets for multi-part answers.
   - Close longer answers with a short, professional offer of further help (e.g., "Let me know if you'd like this explained further.").
   - Avoid emojis, avoid slang, avoid overly casual phrasing.

8. If the user is reading a multi-page document page-by-page ("book mode"), answer strictly using the CURRENT page shown to you, unless the user explicitly references another page number they've already seen.

9. BEFORE responding:
   - Internally verify:
        ✓ No duplicate questions
        ✓ No duplicate options
        ✓ Proper numbering sequence
        ✓ No external knowledge used
        ✓ All content exists in document
        ✓ Tone matches a professional enterprise assistant

REMEMBER:
You have ZERO knowledge outside the uploaded document.
If something is unclear or missing in the document, say so professionally.
Do NOT fabricate. Do NOT assume. Do NOT repeat content unnecessarily.
"""


async def create_session_handler(request):
    try:
        data = await request.json()
    except Exception:
        data = {}
    user_email = (data.get('email') or '').strip().lower() or None
    session_id = session_manager.create_session(user_email=user_email)
    return web.json_response({'session_id': session_id})

async def upload_file_handler(request):
    try:
        reader = await request.multipart()
        session_id = None
        file_data = None
        filename = None
        book_mode = False

        async for part in reader:
            if part.name == 'session_id':
                session_id = await part.text()
            elif part.name == 'book_mode':
                book_mode = (await part.text()).strip().lower() in ('1', 'true', 'yes')
            elif part.name == 'file':
                filename = part.filename
                file_data = await part.read()

        if not session_id or not file_data:
            return web.json_response(
                {'error': 'Missing session_id or file'},
                status=400
            )

        session = session_manager.get_session(session_id)
        if not session:
            return web.json_response(
                {'error': 'Invalid session_id'},
                status=404
            )

        mime_type = get_mime_type(filename)

        if mime_type == 'application/pdf':
            num_pages = check_pdf_pages(file_data)
            if num_pages > 2:
                return web.json_response(
                    {'error': f'PDF has {num_pages} pages. Maximum allowed is 2 pages. Please upload a smaller file.'},
                    status=400
                )

        if not (mime_type.startswith('image/') or mime_type == 'application/pdf'):
            return web.json_response(
                {'error': 'Unsupported file type. Use PDF or image files.'},
                status=400
            )

        base64_data = base64.b64encode(file_data).decode('utf-8')

        if book_mode:
            page_index = session_manager.add_page(session_id, base64_data, filename, mime_type)
            return web.json_response({
                'status': 'success',
                'message': f'Page {page_index + 1} ("{filename}") added to reading queue',
                'file_type': mime_type,
                'page_index': page_index,
                'total_pages': len(session['pages'])
            })

        session_manager.set_file_data(session_id, base64_data, filename, mime_type)

        return web.json_response({
            'status': 'success',
            'message': f'File "{filename}" uploaded successfully',
            'file_type': mime_type
        })

    except Exception as e:
        return web.json_response(
            {'error': f'Upload failed: {str(e)}'},
            status=500
        )

async def set_page_handler(request):
    try:
        data = await request.json()
        session_id = data.get('session_id')
        index = int(data.get('index', 0))
        session = session_manager.get_session(session_id)
        if not session:
            return web.json_response({'error': 'Invalid session_id'}, status=404)
        ok = session_manager.set_current_page(session_id, index)
        if not ok:
            return web.json_response({'error': 'Page index out of range'}, status=400)
        return web.json_response({
            'status': 'success',
            'current_page': index,
            'total_pages': len(session['pages']),
            'file_name': session['file_name']
        })
    except Exception as e:
        return web.json_response({'error': f'Failed to switch page: {str(e)}'}, status=500)

async def query_handler(request):
    try:
        data = await request.json()
        session_id = data.get('session_id')
        query = data.get('query')

        if not session_id or not query:
            return web.json_response(
                {'error': 'Missing session_id or query'},
                status=400
            )

        session = session_manager.get_session(session_id)
        if not session:
            return web.json_response(
                {'error': 'Invalid session_id'},
                status=404
            )

        if not session['file_data']:
            return web.json_response(
                {'error': 'No file uploaded in this session. Please upload a file first.'},
                status=400
            )

        session_manager.add_to_history(session_id, 'user', query)

        messages = [
            {
                'role': 'system',
                'content': create_system_prompt()
            }
        ]

        if len(session['history']) == 1:
            if session['file_type'].startswith('image/'):
                messages.append({
                    'role': 'user',
                    'content': [
                        {
                            'type': 'image_url',
                            'image_url': {
                                'url': f"data:{session['file_type']};base64,{session['file_data']}"
                            }
                        },
                        {
                            'type': 'text',
                            'text': query
                        }
                    ]
                })
            else:
                try:
                    pdf_data = base64.b64decode(session['file_data'])
                    pdf_reader = PyPDF2.PdfReader(BytesIO(pdf_data))
                    pdf_text = ""
                    for page_num in range(len(pdf_reader.pages)):
                        page = pdf_reader.pages[page_num]
                        pdf_text += f"Page {page_num + 1}:\n{page.extract_text()}\n\n"

                    messages.append({
                        'role': 'user',
                        'content': f"Document content from {session['file_name']}:\n\n{pdf_text}\n\nUser question: {query}"
                    })
                except Exception:
                    return web.json_response(
                        {'error': 'Failed to process PDF. Please try uploading an image instead.'},
                        status=500
                    )
        else:
            if session['file_type'].startswith('image/'):
                messages.append({
                    'role': 'user',
                    'content': [
                        {
                            'type': 'image_url',
                            'image_url': {
                                'url': f"data:{session['file_type']};base64,{session['file_data']}"
                            }
                        },
                        {
                            'type': 'text',
                            'text': session['history'][0]['content']
                        }
                    ]
                })
            else:
                try:
                    pdf_data = base64.b64decode(session['file_data'])
                    pdf_reader = PyPDF2.PdfReader(BytesIO(pdf_data))
                    pdf_text = ""
                    for page_num in range(len(pdf_reader.pages)):
                        page = pdf_reader.pages[page_num]
                        pdf_text += f"Page {page_num + 1}:\n{page.extract_text()}\n\n"

                    messages.append({
                        'role': 'user',
                        'content': f"Document content from {session['file_name']}:\n\n{pdf_text}\n\nUser question: {session['history'][0]['content']}"
                    })
                except Exception:
                    pass

            recent_history = session['history'][-10:]

            for msg in recent_history:
                messages.append({
                    'role': msg['role'],
                    'content': msg['content']
                })

        completion = groq_client.chat.completions.create(
            model="qwen/qwen3.8-27b",
            messages=messages,
            temperature=0.7,
            max_tokens=2048,
            top_p=0.9
        )

        response_text = completion.choices[0].message.content

        session_manager.add_to_history(session_id, 'assistant', response_text)

        return web.json_response({
            'response': response_text,
            'file_name': session['file_name'],
            'current_page': session.get('current_page', 0),
            'total_pages': len(session.get('pages', []))
        })

    except Exception as e:
        return web.json_response(
            {'error': f'Query failed: {str(e)}. The AI model may not support this file format. Try uploading an image instead of PDF.'},
            status=500
        )

async def get_history_handler(request):
    session_id = request.match_info.get('session_id')

    session = session_manager.get_session(session_id)
    if not session:
        return web.json_response(
            {'error': 'Invalid session_id'},
            status=404
        )

    return web.json_response({
        'history': session['history'],
        'file_name': session['file_name']
    })

async def get_user_chat_history(request):
    email = request.match_info.get('email', '').strip().lower()
    if not email:
        return json_error("Email is required", 400)
    try:
        res = await run_supabase_sync(
            supabase.table('chat_history')
            .select("id, session_id, role, content, file_name, created_at")
            .eq('user_email', email)
            .order('created_at', desc=True)
            .limit(200)
            .execute
        )
        return web.json_response({"success": True, "history": res.data or []})
    except Exception as e:
        logger.error(f"get_user_chat_history error: {e}", exc_info=True)
        return json_error("Failed to load chat history", 500)

async def clear_history_handler(request):
    data = await request.json()
    session_id = data.get('session_id')

    session = session_manager.get_session(session_id)
    if not session:
        return web.json_response(
            {'error': 'Invalid session_id'},
            status=404
        )

    session['history'] = []
    return web.json_response({'status': 'History cleared'})

# CORS middleware
@web.middleware
async def cors_middleware(request, handler):
    if request.method == 'OPTIONS':
        response = web.Response()
    else:
        response = await handler(request)

    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Methods'] = 'GET, POST, PUT, DELETE, OPTIONS'
    response.headers['Access-Control-Allow-Headers'] = 'Content-Type, X-Auth-Token'
    return response

async def index_handler(request):
    try:
        with open('ai.html', 'r', encoding='utf-8') as f:
            html_content = f.read()
        return web.Response(text=html_content, content_type='text/html')
    except FileNotFoundError:
        return web.Response(text="ai.html file not found!", status=404)


# ────────────────────────────────────────────────
# APP SETUP
# ────────────────────────────────────────────────

def create_app():
    app = web.Application(client_max_size=MAX_FILE_SIZE + 2*1024*1024)
    app.middlewares.append(cors_middleware)
    app.middlewares.append(json_error_middleware)

    app.router.add_post('/api/auth/signup', auth_signup)
    app.router.add_post('/api/auth/login', auth_login)
    app.router.add_get('/api/auth/me', auth_me)

    app.router.add_get('/ai-boat', index_handler)
    app.router.add_post('/api/session/create', create_session_handler)
    app.router.add_post('/api/uploads', upload_file_handler)
    app.router.add_post('/api/session/page', set_page_handler)
    app.router.add_post('/api/query', query_handler)
    app.router.add_get('/api/history/{session_id}', get_history_handler)
    app.router.add_get('/api/chat-history/{email}', get_user_chat_history)
    app.router.add_post('/api/history/clear', clear_history_handler)

    app.router.add_get('/', read_root)
    app.router.add_get('/images', last_read_root)
    app.router.add_get('/whiteboard', at_last_read_root)

    app.router.add_get('/api/files', get_files)
    app.router.add_post('/api/upload', upload_file)
    app.router.add_put('/api/files/{file_id}/update', update_file)
    app.router.add_delete('/api/files/{file_id}/delete', delete_file)
    app.router.add_get('/api/files/{file_id}/download', download_file)

    app.router.add_post('/api/save-url', save_url)
    app.router.add_get('/api/urls', get_urls)
    app.router.add_delete('/api/urls/{url_id}/delete', delete_url)
    app.router.add_get('/api/url/{url_id}', url_redirect)

    logger.info("All routes registered:")
    for r in app.router.routes():
        logger.info(f" {r.method:6} {r.resource.canonical}")
    return app

async def main():
    logger.info("=" * 80)
    logger.info(" FILE MANAGER SERVER - SUPABASE STORAGE ".center(80, "="))
    logger.info(f" Max file size : {MAX_FILE_SIZE//1024//1024} MB")
    logger.info(f" Storage : Supabase PostgreSQL (base64 encoded)")
    logger.info("=" * 80)

    # This is the step that used to require pasting SQL into the Supabase
    # SQL Editor by hand. Now it happens automatically, every time you run
    # this script, using DATABASE_URL.
    await init_database()

    app = create_app()
    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, '0.0.0.0', 9000)
    await site.start()
    logger.info("Server running → http://0.0.0.0:9000")
    logger.info("Press Ctrl+C to stop")
    try:
        await asyncio.Future()
    finally:
        await runner.cleanup()

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logger.info("Server stopped by user")
    except Exception as e:
        logger.critical(f"Fatal error: {e}", exc_info=True)
        sys.exit(1)
